# Generated by Django 5.2.1 on 2025-05-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballclub',
            old_name='attendence',
            new_name='attendance',
        ),
    ]
